export const routeNames = {
  general: {
    landing: "/",
    login: "/login",
    forgetPassword: "/login/forgot-password",
    addService: "/add-service",
    viewService: "/view-services",
    addProject: "/add-project",
    viewProjects: "/view-projects",
    addProduct: "/add-product",
    viewProducts: "/view-products",
    addJob: "/add-job",
    // addJobCategory: "/add-job-category",
    // viewJobCategory: "/view-job-category",
    viewJobs: "/view-jobs",
    jobApplications: "/job-applications",
    addTeam: "/add-team",
    viewTeams: "/view-teams",
    viewXTeams: "/view-xteams",
    addTermsAndConditions: "/add-terms-and-conditions",
    viewTermsAndConditions: "/view-terms-and-conditions",
    addPrivacyPolicy: "/add-privacy-policy",
    viewPrivacyPolicy: "/view-privacy-policy",

    addBlog: "/add-blog",
    viewBlogs: "/view-blogs",
    addTestimonial: "/add-testimonial",
    viewTestimonial: "/view-testimonial",
    addFaq: "/add-faq",
    viewFaq: "/view-faq",
    viewQuotes: "/view-quotes",
    settings: "/settings",
    aboutUs: "/about-us",
  },
};
